@host=http://localhost:3001/api/items

###############################################

# GET all items

GET {{host}}/1

###############################################

# Add item

###############################################

# Update item

###############################################

#Delete item

###############################################